version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    networks:
      - my-app
  db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Na260206
    ports:
      - "5433:5432"
    networks:
      - my-app

networks:
  my-app:
    driver: bridge
